config/routes.rb
Musicoverflow::Application.routes.draw do

  get "sounds/index"
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  resource :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :sounds

  resources :posts do
    resources :comments
  end

  root to: 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments

	accepts_nested_attributes_for :comments, allow_destroy: true
end

app/models/user.rb
require "bcrypt"
class User < ActiveRecord::Base
  include BCrypt
  has_many :posts
  has_many :comments  
  
  # but even if i comment it out the test still passes why???
  validates_presence_of :username, :email, :password
  validates_uniqueness_of :username, :email
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates :password, length: { in: 6..20 }

  

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

  def password
    @password
  end

  def password=(new_password)
    @password = new_password
    self.password_digest = BCrypt::Password.create(new_password)

  end

  def authenticate(test_password)
    if BCrypt::Password.new(self.password_digest) == test_password
      self
    else
      false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  
  def current_user
    current_user ||= User.find(session[:remember_token]) if session[:remember_token]
    
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index

  end

  def create
  	@post = Post.find(params[:post_id])
  	@comment =@post.comments.new(params.require(:comment).permit(:text_comment, :user_id))
    @comment.user_id = current_user.id

  	if @comment.save
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def update
  end

  def destroy
    # NOT WORKING YET
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, :only => [:show, :edit, :update, :destroy]
  
  def welcome
  end

# if the user is not signed in then you can't view the posts and when the user signs in only post NOT created by the user are displayed
  def index
      if !current_user
        @posts= []
      else
      @posts= Post.where.not(user_id: current_user.id).reverse 
    end
  end

# shows the post and the comments related to that post 
  def show
    @post= Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.reverse
  end

 
  def new
    @post= Post.new
  end

  
  def create
    @post =Post.new(params.require(:post).permit(:topic))
    @post.user_id = current_user.id
    
    if @post.save
      redirect_to posts_path
    else
      render 'new'
    end
  end

 
  def edit
    @post= Post.find(params[:id])
  end

  
  def update
    @post= Post.find(params[:id])
    if @post.update_attributes(params.require(:post).permit(:topic))
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

# comments are nested in posts and post_params method permits comments_attributes to be tied to post
  def post_params
    params.require(:post).permit(:topic, 
                                  comments_attributes: [:text_comment])
  end

  def set_post
    @post= Post.find(params[:id])
  end


  def comment_params
    params.require(:comment).permit(:text_comment)
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 def new
  end
 def create
    @user = User.where(:email => params[:session][:email]).first

    if @user == nil || !@user.authenticate(params[:session][:password])
      flash[:error] = "Invalid email/password combination"
      render 'new'
    else
   
      session[:remember_token] = @user.id.to_s
      redirect_to posts_path
    end
  end


  def destroy
    session.delete(:remember_token)
    redirect_to root_path
  end
end

app/controllers/sounds_controller.rb
class SoundsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
  # where the user goes to his profile, this index method only displays posts created by the current user 
  def index
    if params[:filteruser] == "s"
      @posts= Post.where(:user_id => current_user.id).reverse
      puts @posts
    end
  end
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params) 
    if @user.save 
      session[:remember_token] = @user.id
      @current_user = @user
      redirect_to posts_path
    else
      render 'new' 
    end
  end

  def show
    @post= Post.find(params[:id])
    @comment = Comment.new 
    @comments = @post.comments.reverse

  end


  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end

  def post_params
    params.require(:post).permit(:topic, 
                                  comments_attributes: [:text_comment])
  end

  protected

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sounds_helper.rb
module SoundsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/layouts/application.html.erb
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" /> 

  <title><%= content_for?(:title) ? yield(:title) : "MusicOverflow" %></title>
  <link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Quicksand' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Bitter' rel='stylesheet' type='text/css'>



 
  <%= javascript_include_tag 'application', 'vendor/modernizr' %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application' %>
  <%= csrf_meta_tags %>


   <script src="//connect.soundcloud.com/sdk.js"></script>
   

  <!-- In order to access the JavaScript object which provides the SoundCloud Widget API, add this script to your html page. -->
  <script src="/assets/sc_api_player.js"></script>
  

</head>

  

<body>
<div id="container">
  
<div class="fixed">
  <nav class="top-bar" data-topbar data-options>
    <ul class="title-area">
      
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>
   

    <section class="top-bar-section">
      <!-- Left Nav Section -->
     
        <ul class="left">
        <!-- if user not login in or sign up MusicOVerflow Shows up or else if signin => Username Shows up -->
        <% if !current_user %>
         <li><a class="navbar-brand" href="#">MusicOverflow</a></li>
        <% else %>
         <li><a class="navbar-brand" href="#"> <%= link_to current_user.username, users_path(filteruser: 's') %></a></li>
        <% end %>
     


        <!-- if user sign in then only the sign out option shows up or else sign in/sign up shows up -->
        <% if !current_user %>
            <li><%= link_to "Sign Up", new_user_path %></li>
            <li><%= link_to "Sign In", new_sessions_path %></li>
          <% else %>
            <li><%= link_to "Sign Out", sessions_path, :method => :delete %></li>
          <% end %> 
       
        
        </ul>
      
      <!-- Right Nav Section -->
      <ul class="right">
        <li><%= link_to "Random Stream", sounds_path %></a></li>
        <li><%= link_to "String Feed ", posts_path %></li>
        <li><%= link_to "New String", new_post_path %></li>  
      </ul>   
    </section>
  </nav>
</div>



<div class='container'>
  <div class='row'>
    <%= yield %>
  </div>
</div>

</div> <!--end of container -->
</body>
</html>

app/views/posts/_form.html.erb
 <!-- Doesnt allow the user to create a new string unless he is signed in -->
 <div class="panel">
 
 	
 <% if !current_user %>
 	<h3>Sign in/Sign up <br>before you create a new string</h3>
  
  <% else %>
  <h1>New String</h1>	
	<%=form_for @post do |f| %>
		<div class="form_for">
			<div class="small form" id="form_topic">
				<%= f.text_field :topic, placeholder: "String", class: "form-control" %>
			</div>
			

		<%= f.submit %> <br/>
		<%= link_to 'Cancel', posts_path %>
	<%end %>

<% end %> 

</div>
</div>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>try to make it angular so that you dont have to go to another page</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<!-- Show all the posts created but the post index page doesnt include the post created by the current user -->
 <div class="panel">
<% if !current_user %>
	<h3>Sign in/Sign up to view your profile<br> or just random stream a sound</h3>
  
  <% else %>

	<div class= "full-width content-area">
		<div class="row">
			<div class ="large-12 columns">
				<h1>String Feed </h1>
				
				<% @posts.each do |b| %>
	  
	   			<h3><%= b.topic %><h3>    
	      		<p>by <%= b.user.username %></p>
	       		<p><%= link_to "View", post_path(b) %>
	       		  
				<% end %>
			</div>
		</div>
	 </div>
<% end %>
</div>

app/views/posts/new.html.erb
<!-- renders the form in posts -> _form.html.erb -->


<%= render 'form' %>

app/views/posts/show.html.erb
<div class="panel">

	<%= form_for [@post, @comment], url: post_comments_path(@post) do |f| %>
		<fieldset>
			<legend><%= @post.topic  %> </legend>
			 <label>
			 	by <%= @post.user.username %>
			</label>


		<%= f.text_field :text_comment, placeholder: "Add Comment" %>
	
	    <%= f.submit "submit" %>
		</fieldset>
	   
	<% end %>

	<h3> Comments </h3>
	<ul>
		<% @comments.each do |c|%>
			<li><%=c.text_comment%></li>	
			by <%= c.user.username%><br>
			<% if(@comment.user_id == @current_user) %>
				<%= link_to 'Delete', post_comment_path(@post, c),{:method => :delete, confirm: "Are you sure you want to delete this comment?"} %>
			<%end %>
		<% end %>
	</ul>

</div>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/sounds/index.html.erb
<html>
<head>
	
<script src="//connect.soundcloud.com/sdk.js"></script>
<script src="application.js"></script>

</head>
<body>


<table id="">
	<tr>
		
		<td><a href="#" class="genre">house</a></td>
		<td><a href="#" class="genre">trance</a></td>
		<td><a href="#" class="genre">punk</a></td>		
	</tr>
	<tr>
		<td><a href="#" class="genre">deep house</a></td>
		<td><a href="#" class="genre">uplifting trance</a></td>
		<td><a href="#" class="genre">rock</a></td>
	</tr>
	<tr>
		<td><a href="#" class="genre">progressive house</a></td>
		<td><a href="#" class="genre">hard trance</a></td>
		<td><a href="#" class="genre">jazz</a></td>
	</tr>
	<tr>
		<td><a href="#" class="genre">techno</a></td>
		<td><a href="#" class="genre">psy trance</a></td>
		<td><a href="#" class="genre">classical</a></td>
	</tr>
	<tr>
		<td><a href="#" class="genre">electronic</a></td>
		<td><a href="#" class="genre">dark techno</a></td>
		<td><a href="#" class="genre">trap</a></td>
	</tr>

</table>
<div id= "target">
</div>
 <script >
	 // calls on the SC API and allows the user to stream a random sound based on the music genre selected
	 function playSomeSound(genre){
		SC.get('/tracks', {
			"tags": genre,
			"downloadable": true},
		function(tracks){
			var random= Math.floor(Math.random() * 100);
			SC.oEmbed(tracks[random].uri, { auto_play: true }, document.getElementById('target'));
			});
		};

	window.onload =function() {
		SC.initialize({
			client_id: '4aa1dd0180daa6f5578cf7fb34e07645'
		});
		$('.genre').click(function(e){
				e.preventDefault();
				playSomeSound(this.innerHTML);
			});
		};
</script>

</body>

</html>

app/views/users/index.html.erb
<div class="panel">
	<div class= "full-width content-area">
		<div class="row">
			<div class ="large-12 columns">
				<h1>Your Profile<%#= current_user.username %></h1>
					<% @posts.each do |b| %>
	 
	    			<h3><%= b.topic %></h3>   
	     			
	     			
	       			<div class="button1"><%= link_to "View", user_path(b) %>
	       			<%= link_to "Delete", post_path(b), {method: :delete, confirm: "Are you sure you want to delete this event"} %></div>
	 
					<% end %>
			</div>
		</div>
	 </div>
</div>

app/views/users/new.html.erb
<!-- form to sign up -->
<form>
	<div class= "panel">
		<h1>New User</h1>

		<div class = "row">

			<%= form_for @user do |f| %>
			
			  <%= f.text_field :username, placeholder: "Username" %>
			  <%= f.text_field :email, placeholder: "Email" %>
			  <%= f.password_field :password, placeholder: "Password" %>
			  <%= f.submit %>

			<%end %>

		

  </div>

app/views/users/show.html.erb
<div class="panel">

	<%= form_for [@post, @comment], url: post_comments_path(@post) do |f| %>
		<fieldset>
			<legend><%= @post.topic  %> </legend>
			 <label>
			 	by <%= @post.user.username %>
			</label>

		<%= f.text_field :text_comment, placeholder: "Add Comment" %>
	   <%= f.submit "submit" %>
		</fieldset>
	   
	<% end %>

	<h3> Comments </h3>
	<ul>
		<% @comments.each do |c|%>
			<li><%=c.text_comment%></li>	
			by <%= c.user.username %>			
		<%end %>
	</ul>

</div>